### ISSUE TITLE
进入yacd后闪退

### ISSUE THREAD

**Issue by mataxiangyun** [hypooo/clash-host#1]
感谢大大的一键部署

我在前几天在极空间nas上成功部署，正常使用，但是今天打开yacd的时候，没法进入面板，停留在api的输入面板。输入对应的后端端口进入后会闪退，或者所有界面内容为空。
尝试删除容器重新部署，仍然无法进入
![微信截图_20241223104801](https://github.com/user-attachments/assets/82b61c84-96ee-4a25-9d4e-a02a182f9150)

**Comment by hypooo** [comment]
不知道什么原因，最近又优化了一下，可以重新拉代码部署下试试

**Comment by mataxiangyun** [comment]
感谢大大！
